### ISSUE TITLE
Contract returns null when data is transferred through set() and get() and stored locally on implementation

### ISSUE THREAD

**Issue by InfinityGhost** [jacqueskang/IpcServiceFramework#116]
**Describe the bug**
Contract returns null when data is requested through a set() and get() data flow. I'm not sure if I'm doing something wrong here or not, but from debugging alone there's nothing I can tell I've done wrong in my project. 

**Contract**
- https://github.com/InfinityGhost/OpenTabletDriver/blob/eto/TabletDriverLib/Contracts/IDriverDaemon.cs

**Implementation**
- https://github.com/InfinityGhost/OpenTabletDriver/blob/eto/OpenTabletDriverDaemon/DriverDaemon.cs

**Host**
- https://github.com/InfinityGhost/OpenTabletDriver/blob/eto/OpenTabletDriverDaemon/Program.cs

**Client**
- https://github.com/InfinityGhost/OpenTabletDriver/blob/eto/OpenTabletDriverUX/MainForm.cs

**To Reproduce**
1. Create data contract that transfers data with a Set() and Get() method
2. Store the data on the contract class when set
3. Returns null if set from Set() method

**Expected behavior**
Should return the requested objects with the Get() method because it should be stored in the local value in the class.

**Comment by jacqueskang** [comment]
Hi @InfinityGhost, In the hosting app you registered the service implementation using `services.AddScoped<IDriverDaemon, DriverDaemon>()`

This tells the DI to resolve a new instance for every scope. The framework creates a scope for every request which explains the behavior you described.

You can try registering DriverDaemon with AddSingleton. But then you need to be careful about concurrent access because IPC host creates multiple listener threads by default (the number can be configured to 1 through).

If this helps please consider closing this issue.

**Comment by InfinityGhost** [comment]
Thanks dude that fixed it, I'm new to DI in general. I don't think that concurrent access is likely to become a problem because my app is designed to only be controlled by a single app at any time anyway with minimal data transfers.
