### ISSUE TITLE
Serialization errors can terminate the server

### ISSUE THREAD

**Issue by pablocar80** [jacqueskang/IpcServiceFramework#74]
**Describe the bug**
Calling a server method with parameters that fail to serialize/deserialize may crash the server with a "pipe is broken" exception.

**To Reproduce**
1. Create a client/server app that uses named pipes
2. Create a method that passes a class which includes a field of type IPAddress
3. Execute a call from client to server
4. See the following error:

![image](https://user-images.githubusercontent.com/36197603/57141533-0514c700-6d80-11e9-8dae-bd97eb8cd110.png)

**Expected behavior**
The bad request shouldn't terminate the server, instead, the client should receive and yield an exception.

**Screenshots**
See screenshot above

**Comment by jacqueskang** [comment]
Resolved for V3 in the following way:

1. If failed to serialize request (any input parameter): client will receive IpcSerializationException
   - Server side will raise an IpcCommunicationException in the process thread since connection is already established by client but won't terminate.
2. If failed to serialize response: client will receive IpcFaultException with status "InternalServerError"
